version: '3.9'

services:
  frontend:
    image: node:16-alpine
    container_name: polyshop_frontend
    ports:
      - 3000:3000
    volumes:
      - $PWD:/app
    command: /bin/sh -c "cd /app && npm run start"
    networks:
      - spring_microservices

networks:
  spring_microservices:
    external: true
    